// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:d84391b1-a821-41ed-9665-141263c71a80",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_xkkofwXuO",
    "aws_user_pools_web_client_id": "3im9e1sn451na75n1evr6585ju",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://gxwcd6mkojczxlxomlmmnbig2i.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS"
};


export default awsmobile;
