// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-west-1",
    "aws_cognito_identity_pool_id": "eu-west-1:86dbe490-5eec-4e23-9abd-739ab85b5813",
    "aws_cognito_region": "eu-west-1",
    "aws_user_pools_id": "eu-west-1_3NlhFFhS1",
    "aws_user_pools_web_client_id": "6hgs1i8hf8fbjvb2g0fbb6j5h9",
    "oauth": {}
};


export default awsmobile;
